/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MediPee;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Usuario
 */
public class VentanaEditor extends javax.swing.JFrame {
conectar cc = new conectar();
Connection cn = cc.conexion();
private int codigo;
DefaultTableModel model;
    /**
     * Creates new form VentanaEditor
     */
    public VentanaEditor() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/interfaz/medipee.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        cargarTabla("");
        getContentPane().setBackground(new Color(41,41,41));
    }
    
    void cargarDatos() {
        try {
            int codFinal;
            float altura;
            float peso;
            float ph; 
            ph = Float.parseFloat(txtfPh.getText());
            altura = Float.parseFloat(txtfAltura.getText());
            peso = Float.parseFloat(txtfPeso.getText());
            float imc = peso / ((altura) * (altura));
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM datos_encuestados LIMIT 0, 1000");
            rs.last();
            st.executeUpdate("UPDATE datos_encuestados SET altura = "+altura+", pH = "+ph+", peso = "+peso+" WHERE codEncuestado = "+codigo);
            txtfAltura.setText("");
            txtfPeso.setText("");
            txtfPh.setText("");
            txtfCodigo.setText("");
            cargarTabla("");
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al cargar los datos");
        }
    }
    
    void cargarTabla(String valor) {
        String mostrar = "SELECT * FROM datos_encuestados "
                + "WHERE CONCAT(codEncuestado, pH, altura, peso, imc) "
                + "LIKE '%" + valor + "%'";
        String[] titulos = {"Codigo", "pH", "Altura", "Peso", "IMC"};
        String[] Registros = new String[6];
        model = new DefaultTableModel(null, titulos);
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(mostrar);
            while (rs.next()) {
                Registros[0] = rs.getString("codEncuestado");
                Registros[1] = rs.getString("pH");
                Registros[2] = rs.getString("altura");
                Registros[3] = rs.getString("peso");
                Registros[4] = rs.getString("imc");
                model.addRow(Registros);
            }
            rs.first();
            jTableDatos_02.setModel(model);
            int codFinal = 1;
            while (rs.next()) {
                codFinal = codFinal + 1;
            }
            String codFinalString = String.valueOf(codFinal);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al leer la tabla");
        }


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDatos_02 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtfAltura = new javax.swing.JTextField();
        txtfPeso = new javax.swing.JTextField();
        txtfPh = new javax.swing.JTextField();
        txtfCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDatos_02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableDatos_02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableDatos_02.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableDatos_02);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 11, 470, 573));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfAltura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfAlturaKeyPressed(evt);
            }
        });
        jPanel1.add(txtfAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 107, 35));

        txtfPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfPesoKeyPressed(evt);
            }
        });
        jPanel1.add(txtfPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 107, 35));

        txtfPh.setBackground(new java.awt.Color(255, 255, 153));
        txtfPh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtfPh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPhActionPerformed(evt);
            }
        });
        jPanel1.add(txtfPh, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 107, 37));

        txtfCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 219, 107, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/panel editor.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));

        jButtonSalir.setBackground(new java.awt.Color(153, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 363, 130, 30));

        jbtnModificar.setBackground(new java.awt.Color(51, 51, 51));
        jbtnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 120, 30));

        btnGuardar.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 319, 120, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Altura");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("pH: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 63, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Peso");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 171, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Código");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 222, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 106, 300, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/ventana de edicion.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfAlturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAlturaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfPeso.requestFocus();
        }
    }//GEN-LAST:event_txtfAlturaKeyPressed

    private void txtfPesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPesoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cargarDatos();
            txtfAltura.requestFocus();
        }
    }//GEN-LAST:event_txtfPesoKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        txtfAltura.setText("");
        txtfPeso.setText("");
        txtfPh.setText("");
        
        codigo = Integer.parseInt(txtfCodigo.getText());
        String mostrar = "SELECT * FROM datos_encuestados "
                + "WHERE codEncuestado = "+codigo;
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(mostrar);
            while (rs.next()) {
                txtfAltura.setText(rs.getString("altura"));
                txtfPeso.setText(rs.getString("peso"));
                txtfPh.setText(rs.getString("ph"));
                
            }
            rs.first();
            int codFinal = 1;
            while (rs.next()) {
                codFinal = codFinal + 1;
            }
            String codFinalString = String.valueOf(codFinal);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAdmin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hubo un error al leer la tabla");
        }
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void txtfPhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDatos_02;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JTextField txtfAltura;
    private javax.swing.JTextField txtfCodigo;
    private javax.swing.JTextField txtfPeso;
    private javax.swing.JTextField txtfPh;
    // End of variables declaration//GEN-END:variables
}
